apiVersion: apps/v1
kind: Deployment
metadata:
  name: phone-validator-backend-deployment
  labels:
    app: phone-validator-backend
    product: phone-validator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phone-validator-backend
  strategy: 
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: phone-validator-backend
        product: phone-validator
    spec:
      containers:
      - image: johnylima/phone-validator-backend-2:14
        name: phone-validator-backend
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
            - name: backend-port
              containerPort: 8080
              hostPort: 8080

status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: phone-validator-backend-service
  labels:
    app: phone-validator-backend
    product: phone-validator
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8081
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8081
  selector:
    app: phone-validator-backend

---

apiVersion: v1
kind: Service
metadata:
  name: phone-validator-backend-loadbalancer
  labels:
    app: phone-validator-backend
    product: phone-validator
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: phone-validator-backend