apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: phone-validator-frontend
  name: phone-validator-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phone-validator-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: phone-validator-frontend
    spec:
      containers:
      - image: johnylima/phone-validator-frontend-2:4
        name: phone-validator-frontend
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 8081
        env:
        - name: phone-validator
          value: "phone-validator-backend"

status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-phone-validator-frontend
  labels:
    app: lb-phone-validator-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 5000
  selector:
    app: phone-validator-frontend
